const names = {
  English: {
    month: [
      { name: "January", style: "long" },
      { name: "Jan", style: "short" },
      { name: "February", style: "long" },
      { name: "Feb", style: "short" },
      { name: "March", style: "long" },
      { name: "Mar", style: "short" },
      { name: "April", style: "long" },
      { name: "Apr", style: "short" },
      { name: "May", style: "long" },
      { name: "May", style: "short" },
      { name: "June", style: "long" },
      { name: "Jun", style: "short" },
      { name: "July", style: "long" },
      { name: "Jul", style: "short" },
      { name: "August", style: "long" },
      { name: "Aug", style: "short" },
      { name: "September", style: "long" },
      { name: "Sep", style: "short" },
      { name: "October", style: "long" },
      { name: "Oct", style: "short" },
      { name: "November", style: "long" },
      { name: "Nov", style: "short" },
      { name: "December", style: "long" },
      { name: "Dec", style: "short" },
    ],
    weekday: [
      { name: "Wednesday", style: "long" },
      { name: "Wed", style: "short" },
      { name: "Thursday", style: "long" },
      { name: "Thu", style: "short" },
      { name: "Friday", style: "long" },
      { name: "Fri", style: "short" },
      { name: "Saturday", style: "long" },
      { name: "Sat", style: "short" },
      { name: "Sunday", style: "long" },
      { name: "Sun", style: "short" },
      { name: "Monday", style: "long" },
      { name: "Mon", style: "short" },
      { name: "Tuesday", style: "long" },
      { name: "Tue", style: "short" },
    ],
  },
  Chinese: {
    month: [
      { name: "一月", style: "long" },
      { name: "1月", style: "short" },
      { name: "二月", style: "long" },
      { name: "2月", style: "short" },
      { name: "三月", style: "long" },
      { name: "3月", style: "short" },
      { name: "四月", style: "long" },
      { name: "4月", style: "short" },
      { name: "五月", style: "long" },
      { name: "5月", style: "short" },
      { name: "六月", style: "long" },
      { name: "6月", style: "short" },
      { name: "七月", style: "long" },
      { name: "7月", style: "short" },
      { name: "八月", style: "long" },
      { name: "8月", style: "short" },
      { name: "九月", style: "long" },
      { name: "9月", style: "short" },
      { name: "十月", style: "long" },
      { name: "10月", style: "short" },
      { name: "十一月", style: "long" },
      { name: "11月", style: "short" },
      { name: "十二月", style: "long" },
      { name: "12月", style: "short" },
    ],
    weekday: [
      { name: "星期三", style: "long" },
      { name: "周三", style: "short" },
      { name: "星期四", style: "long" },
      { name: "周四", style: "short" },
      { name: "星期五", style: "long" },
      { name: "周五", style: "short" },
      { name: "星期六", style: "long" },
      { name: "周六", style: "short" },
      { name: "星期日", style: "long" },
      { name: "周日", style: "short" },
      { name: "星期一", style: "long" },
      { name: "周一", style: "short" },
      { name: "星期二", style: "long" },
      { name: "周二", style: "short" },
    ],
  },
  Russian: {
    month: [
      { name: "январь", style: "long" },
      { name: "янв.", style: "short" },
      { name: "февраль", style: "long" },
      { name: "февр.", style: "short" },
      { name: "март", style: "long" },
      { name: "март", style: "short" },
      { name: "апрель", style: "long" },
      { name: "апр.", style: "short" },
      { name: "май", style: "long" },
      { name: "май", style: "short" },
      { name: "июнь", style: "long" },
      { name: "июнь", style: "short" },
      { name: "июль", style: "long" },
      { name: "июль", style: "short" },
      { name: "август", style: "long" },
      { name: "авг.", style: "short" },
      { name: "сентябрь", style: "long" },
      { name: "сент.", style: "short" },
      { name: "октябрь", style: "long" },
      { name: "окт.", style: "short" },
      { name: "ноябрь", style: "long" },
      { name: "нояб.", style: "short" },
      { name: "декабрь", style: "long" },
      { name: "дек.", style: "short" },
    ],
    weekday: [
      { name: "среда", style: "long" },
      { name: "ср", style: "short" },
      { name: "четверг", style: "long" },
      { name: "чт", style: "short" },
      { name: "пятница", style: "long" },
      { name: "пт", style: "short" },
      { name: "суббота", style: "long" },
      { name: "сб", style: "short" },
      { name: "воскресенье", style: "long" },
      { name: "вс", style: "short" },
      { name: "понедельник", style: "long" },
      { name: "пн", style: "short" },
      { name: "вторник", style: "long" },
      { name: "вт", style: "short" },
    ],
  },
  German: {
    month: [
      { name: "Januar", style: "long" },
      { name: "Jan", style: "short" },
      { name: "Februar", style: "long" },
      { name: "Feb", style: "short" },
      { name: "März", style: "long" },
      { name: "Mär", style: "short" },
      { name: "April", style: "long" },
      { name: "Apr", style: "short" },
      { name: "Mai", style: "long" },
      { name: "Mai", style: "short" },
      { name: "Juni", style: "long" },
      { name: "Jun", style: "short" },
      { name: "Juli", style: "long" },
      { name: "Jul", style: "short" },
      { name: "August", style: "long" },
      { name: "Aug", style: "short" },
      { name: "September", style: "long" },
      { name: "Sep", style: "short" },
      { name: "Oktober", style: "long" },
      { name: "Okt", style: "short" },
      { name: "November", style: "long" },
      { name: "Nov", style: "short" },
      { name: "Dezember", style: "long" },
      { name: "Dez", style: "short" },
    ],
    weekday: [
      { name: "Mittwoch", style: "long" },
      { name: "Mi", style: "short" },
      { name: "Donnerstag", style: "long" },
      { name: "Do", style: "short" },
      { name: "Freitag", style: "long" },
      { name: "Fr", style: "short" },
      { name: "Samstag", style: "long" },
      { name: "Sa", style: "short" },
      { name: "Sonntag", style: "long" },
      { name: "So", style: "short" },
      { name: "Montag", style: "long" },
      { name: "Mo", style: "short" },
      { name: "Dienstag", style: "long" },
      { name: "Di", style: "short" },
    ],
  },
  Romanian: {
    month: [
      { name: "ianuarie", style: "long" },
      { name: "ian.", style: "short" },
      { name: "februarie", style: "long" },
      { name: "feb.", style: "short" },
      { name: "martie", style: "long" },
      { name: "mar.", style: "short" },
      { name: "aprilie", style: "long" },
      { name: "apr.", style: "short" },
      { name: "mai", style: "long" },
      { name: "mai", style: "short" },
      { name: "iunie", style: "long" },
      { name: "iun.", style: "short" },
      { name: "iulie", style: "long" },
      { name: "iul.", style: "short" },
      { name: "august", style: "long" },
      { name: "aug.", style: "short" },
      { name: "septembrie", style: "long" },
      { name: "sept.", style: "short" },
      { name: "octombrie", style: "long" },
      { name: "oct.", style: "short" },
      { name: "noiembrie", style: "long" },
      { name: "nov.", style: "short" },
      { name: "decembrie", style: "long" },
      { name: "dec.", style: "short" },
    ],
    weekday: [
      { name: "miercuri", style: "long" },
      { name: "mie.", style: "short" },
      { name: "joi", style: "long" },
      { name: "joi", style: "short" },
      { name: "vineri", style: "long" },
      { name: "vin.", style: "short" },
      { name: "sâmbătă", style: "long" },
      { name: "sâm.", style: "short" },
      { name: "duminică", style: "long" },
      { name: "dum.", style: "short" },
      { name: "luni", style: "long" },
      { name: "lun.", style: "short" },
      { name: "marți", style: "long" },
      { name: "mar.", style: "short" },
    ],
  },
  Polish: {
    month: [
      { name: "styczeń", style: "long" },
      { name: "sty", style: "short" },
      { name: "luty", style: "long" },
      { name: "lut", style: "short" },
      { name: "marzec", style: "long" },
      { name: "mar", style: "short" },
      { name: "kwiecień", style: "long" },
      { name: "kwi", style: "short" },
      { name: "maj", style: "long" },
      { name: "maj", style: "short" },
      { name: "czerwiec", style: "long" },
      { name: "cze", style: "short" },
      { name: "lipiec", style: "long" },
      { name: "lip", style: "short" },
      { name: "sierpień", style: "long" },
      { name: "sie", style: "short" },
      { name: "wrzesień", style: "long" },
      { name: "wrz", style: "short" },
      { name: "październik", style: "long" },
      { name: "paź", style: "short" },
      { name: "listopad", style: "long" },
      { name: "lis", style: "short" },
      { name: "grudzień", style: "long" },
      { name: "gru", style: "short" },
    ],
    weekday: [
      { name: "środa", style: "long" },
      { name: "śr.", style: "short" },
      { name: "czwartek", style: "long" },
      { name: "czw.", style: "short" },
      { name: "piątek", style: "long" },
      { name: "pt.", style: "short" },
      { name: "sobota", style: "long" },
      { name: "sob.", style: "short" },
      { name: "niedziela", style: "long" },
      { name: "niedz.", style: "short" },
      { name: "poniedziałek", style: "long" },
      { name: "pon.", style: "short" },
      { name: "wtorek", style: "long" },
      { name: "wt.", style: "short" },
    ],
  },
  Hungarian: {
    month: [
      { name: "január", style: "long" },
      { name: "jan.", style: "short" },
      { name: "február", style: "long" },
      { name: "febr.", style: "short" },
      { name: "március", style: "long" },
      { name: "márc.", style: "short" },
      { name: "április", style: "long" },
      { name: "ápr.", style: "short" },
      { name: "május", style: "long" },
      { name: "máj.", style: "short" },
      { name: "június", style: "long" },
      { name: "jún.", style: "short" },
      { name: "július", style: "long" },
      { name: "júl.", style: "short" },
      { name: "augusztus", style: "long" },
      { name: "aug.", style: "short" },
      { name: "szeptember", style: "long" },
      { name: "szept.", style: "short" },
      { name: "október", style: "long" },
      { name: "okt.", style: "short" },
      { name: "november", style: "long" },
      { name: "nov.", style: "short" },
      { name: "december", style: "long" },
      { name: "dec.", style: "short" },
    ],
    weekday: [
      { name: "szerda", style: "long" },
      { name: "Sze", style: "short" },
      { name: "csütörtök", style: "long" },
      { name: "Cs", style: "short" },
      { name: "péntek", style: "long" },
      { name: "P", style: "short" },
      { name: "szombat", style: "long" },
      { name: "Szo", style: "short" },
      { name: "vasárnap", style: "long" },
      { name: "V", style: "short" },
      { name: "hétfő", style: "long" },
      { name: "H", style: "short" },
      { name: "kedd", style: "long" },
      { name: "K", style: "short" },
    ],
  },
  Slovak: {
    month: [
      { name: "január", style: "long" },
      { name: "jan", style: "short" },
      { name: "február", style: "long" },
      { name: "feb", style: "short" },
      { name: "marec", style: "long" },
      { name: "mar", style: "short" },
      { name: "apríl", style: "long" },
      { name: "apr", style: "short" },
      { name: "máj", style: "long" },
      { name: "máj", style: "short" },
      { name: "jún", style: "long" },
      { name: "jún", style: "short" },
      { name: "júl", style: "long" },
      { name: "júl", style: "short" },
      { name: "august", style: "long" },
      { name: "aug", style: "short" },
      { name: "september", style: "long" },
      { name: "sep", style: "short" },
      { name: "október", style: "long" },
      { name: "okt", style: "short" },
      { name: "november", style: "long" },
      { name: "nov", style: "short" },
      { name: "december", style: "long" },
      { name: "dec", style: "short" },
    ],
    weekday: [
      { name: "streda", style: "long" },
      { name: "st", style: "short" },
      { name: "štvrtok", style: "long" },
      { name: "št", style: "short" },
      { name: "piatok", style: "long" },
      { name: "pi", style: "short" },
      { name: "sobota", style: "long" },
      { name: "so", style: "short" },
      { name: "nedeľa", style: "long" },
      { name: "ne", style: "short" },
      { name: "pondelok", style: "long" },
      { name: "po", style: "short" },
      { name: "utorok", style: "long" },
      { name: "ut", style: "short" },
    ],
  },
  Spanish: {
    month: [
      { name: "enero", style: "long" },
      { name: "ene", style: "short" },
      { name: "febrero", style: "long" },
      { name: "feb", style: "short" },
      { name: "marzo", style: "long" },
      { name: "mar", style: "short" },
      { name: "abril", style: "long" },
      { name: "abr", style: "short" },
      { name: "mayo", style: "long" },
      { name: "may", style: "short" },
      { name: "junio", style: "long" },
      { name: "jun", style: "short" },
      { name: "julio", style: "long" },
      { name: "jul", style: "short" },
      { name: "agosto", style: "long" },
      { name: "ago", style: "short" },
      { name: "septiembre", style: "long" },
      { name: "sept", style: "short" },
      { name: "octubre", style: "long" },
      { name: "oct", style: "short" },
      { name: "noviembre", style: "long" },
      { name: "nov", style: "short" },
      { name: "diciembre", style: "long" },
      { name: "dic", style: "short" },
    ],
    weekday: [
      { name: "miércoles", style: "long" },
      { name: "mié", style: "short" },
      { name: "jueves", style: "long" },
      { name: "jue", style: "short" },
      { name: "viernes", style: "long" },
      { name: "vie", style: "short" },
      { name: "sábado", style: "long" },
      { name: "sáb", style: "short" },
      { name: "domingo", style: "long" },
      { name: "dom", style: "short" },
      { name: "lunes", style: "long" },
      { name: "lun", style: "short" },
      { name: "martes", style: "long" },
      { name: "mar", style: "short" },
    ],
  },
  Italian: {
    month: [
      { name: "gennaio", style: "long" },
      { name: "gen", style: "short" },
      { name: "febbraio", style: "long" },
      { name: "feb", style: "short" },
      { name: "marzo", style: "long" },
      { name: "mar", style: "short" },
      { name: "aprile", style: "long" },
      { name: "apr", style: "short" },
      { name: "maggio", style: "long" },
      { name: "mag", style: "short" },
      { name: "giugno", style: "long" },
      { name: "giu", style: "short" },
      { name: "luglio", style: "long" },
      { name: "lug", style: "short" },
      { name: "agosto", style: "long" },
      { name: "ago", style: "short" },
      { name: "settembre", style: "long" },
      { name: "set", style: "short" },
      { name: "ottobre", style: "long" },
      { name: "ott", style: "short" },
      { name: "novembre", style: "long" },
      { name: "nov", style: "short" },
      { name: "dicembre", style: "long" },
      { name: "dic", style: "short" },
    ],
    weekday: [
      { name: "mercoledì", style: "long" },
      { name: "mer", style: "short" },
      { name: "giovedì", style: "long" },
      { name: "gio", style: "short" },
      { name: "venerdì", style: "long" },
      { name: "ven", style: "short" },
      { name: "sabato", style: "long" },
      { name: "sab", style: "short" },
      { name: "domenica", style: "long" },
      { name: "dom", style: "short" },
      { name: "lunedì", style: "long" },
      { name: "lun", style: "short" },
      { name: "martedì", style: "long" },
      { name: "mar", style: "short" },
    ],
  },
  French: {
    month: [
      { name: "janvier", style: "long" },
      { name: "janv.", style: "short" },
      { name: "février", style: "long" },
      { name: "févr.", style: "short" },
      { name: "mars", style: "long" },
      { name: "mars", style: "short" },
      { name: "avril", style: "long" },
      { name: "avr.", style: "short" },
      { name: "mai", style: "long" },
      { name: "mai", style: "short" },
      { name: "juin", style: "long" },
      { name: "juin", style: "short" },
      { name: "juillet", style: "long" },
      { name: "juil.", style: "short" },
      { name: "août", style: "long" },
      { name: "août", style: "short" },
      { name: "septembre", style: "long" },
      { name: "sept.", style: "short" },
      { name: "octobre", style: "long" },
      { name: "oct.", style: "short" },
      { name: "novembre", style: "long" },
      { name: "nov.", style: "short" },
      { name: "décembre", style: "long" },
      { name: "déc.", style: "short" },
    ],
    weekday: [
      { name: "mercredi", style: "long" },
      { name: "mer.", style: "short" },
      { name: "jeudi", style: "long" },
      { name: "jeu.", style: "short" },
      { name: "vendredi", style: "long" },
      { name: "ven.", style: "short" },
      { name: "samedi", style: "long" },
      { name: "sam.", style: "short" },
      { name: "dimanche", style: "long" },
      { name: "dim.", style: "short" },
      { name: "lundi", style: "long" },
      { name: "lun.", style: "short" },
      { name: "mardi", style: "long" },
      { name: "mar.", style: "short" },
    ],
  },
};
module.exports = { names };
